import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StorageProvider } from "@/components/storage";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* react-scan: https://github.com/aidenybai/react-scan */}
      {process.env.NODE_ENV === "development" && (
        <head>
          <script
            src="https://unpkg.com/react-scan/dist/auto.global.js"
            async
          />
        </head>
      )}
      <body className={inter.className}>
        <StorageProvider>{children}</StorageProvider>
      </body>
    </html>
  );
}
